# Basic intro
## Basic syntax and array methods

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
b = np.array([[1,3,4], [5,3,2]])
print(b)

[[1 3 4]
 [5 3 2]]


In [4]:
# to get dimension of an array
a.ndim

1

In [5]:
b.ndim

2

In [6]:
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [7]:
#get a specific element
b[1,2]
#change it
b[1,2] = 8
b

array([[1, 3, 4],
       [5, 3, 8]])

In [8]:
print(b[0])

[1 3 4]


In [9]:
# Getting a specific column
print(b[:, 2])

[4 8]


In [10]:
b[:, 2] = [10, 15]
b

array([[ 1,  3, 10],
       [ 5,  3, 15]])

In [11]:
zero_list = np.zeros(4)
zero_list

array([0., 0., 0., 0.])

## Matrix methods 

In [12]:
# getting a 0 matrix
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# generating a identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
# wanting a different number other than 0
np.full((3,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [15]:
#Random numbers array
np.random.rand(2, 5)
# the parameters is the shape of the array and not the upper and lower limits

array([[0.70702547, 0.43100647, 0.45965895, 0.32918601, 0.65733939],
       [0.25987564, 0.30954497, 0.56588267, 0.15989181, 0.97869827]])

In [16]:
#random interger 
np.random.randint(2,6, size = (3,5))

array([[4, 2, 5, 4, 2],
       [4, 2, 4, 4, 3],
       [3, 4, 5, 3, 5]])

In [17]:
# repeat an array
arr = np.array([[1,2,3]])
arr2 = np.repeat(arr, 3, axis = 0)
arr3 = np.repeat(arr, 3, axis = 1)
print(arr2)
print(arr3)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [18]:
output = np.full((5,5), 1)
z = np.zeros((3,3))
z[1,1] = 9
output[1:4, 1:4] = z
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Copying an array

#### Careful while copying an array!

In [19]:
a = np.array([1,2,3,4])
b = a
b[0] = 100
print(b)
print(a)

[100   2   3   4]
[100   2   3   4]


Here b = a basically says b points to a so changing any number in array b changes the original. b isn't a copy of a. **The same goes for lists.**

In [20]:
a = np.array([1,2,3,4])
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3   4]
[1 2 3 4]


## Reorganizing arrays

In [21]:
# Changing shape of array
before = np.array([[1,2,3,4,5,6],[6,7,8,9,0,1]])
print (before)
after = before.reshape(3,4)
print (after)
after2 = before.reshape(2,2,3)
print(after2)

[[1 2 3 4 5 6]
 [6 7 8 9 0 1]]
[[1 2 3 4]
 [5 6 6 7]
 [8 9 0 1]]
[[[1 2 3]
  [4 5 6]]

 [[6 7 8]
  [9 0 1]]]


In [22]:
# vertical stack
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [23]:
# horizontal array
h1 = np.array([1,2,3,4])
h2 = np.array([5,6,7,8])
np.hstack([h1,h2,h2])

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8])

## Loading data from file

In [24]:
filedata = np.genfromtxt('data.txt', delimiter=',')
print(filedata)
print(filedata.astype('int32'))

[  1.   2.   3.   4.   3.   5.   3.   2.   3.   4.   5.   2.   3.   4.
  58. 382.  39.  58.  79.  80.]
[  1   2   3   4   3   5   3   2   3   4   5   2   3   4  58 382  39  58
  79  80]
