# Mathematics 
## Some basic maths

In [1]:
import numpy as np
a = np.array([1,2,3,4])

In [2]:
a = a+2
print(a)

[3 4 5 6]


In [3]:
a = a-2
print(a)
a = a*3
print(a)

[1 2 3 4]
[ 3  6  9 12]


In [4]:
a = a ** 2
print(a)

[  9  36  81 144]


In [5]:
print(np.sin(a))

[ 0.41211849 -0.99177885 -0.62988799 -0.49102159]


In [6]:
b = np.array([3,2,5,3])
print(a + b)
print(a*b)
print(np.sin(a-b))

[ 12  38  86 147]
[ 27  72 405 432]
[-0.2794155   0.52908269  0.56610764  0.36317137]


## Linear algebra

In [7]:
a = np.random.randint(1, 10, (4, 2))
b = np.random.randint(1, 10, (2, 3))
print(a)
print(b)

[[7 7]
 [4 5]
 [8 2]
 [3 2]]
[[9 4 2]
 [5 9 7]]


In [8]:
# matrix multiplication
print(np.matmul(a,b))

[[98 91 63]
 [61 61 43]
 [82 50 30]
 [37 30 20]]


In [9]:
# find the determinant
c = np.identity(3)
np.linalg.det(c)
# since the determinant value of identity matrix is 1

1.0

## Statistics

In [10]:
stats = np.array([[1,2,3], [4,5,6]])

In [11]:
print(np.min(stats, axis = 1))

[1 4]


In [12]:
print(np.min(stats))
print(np.max(stats))

1
6


In [13]:
# sum of all elements in the array
print(np.sum(stats))

21
